name: Python Package Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine pytest build theophanie_models

      - name: Write PyPI auth secret for BuildKit
        run: | 
          echo -e "[global]" > pip.conf
          echo -e "index-url = https://${{ secrets.HERA_USERNAME }}:${{ secrets.HERA_PASSWORD }}@hera.delmasweb.net/simple" >> pip.conf
          echo -e "trusted-host = hera.delmasweb.net" >> pip.conf
          
      - name: Run unit tests
        run: |
          cd logger  
          pytest tests/
    
      - name: Extract tag version and update setup.py
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          echo "Detected version: $VERSION"
          sed -i "s/version = ['\"]\([^'\"]*\)['\"]/version = '$VERSION'/" pyproject.toml
          sed -i "s/__version__ = ['\"]\([^'\"]*\)['\"]/__version__ = '$VERSION'/" logger/__init__.py

      - name: Clean previous builds
        run: |
          rm -rf dist/
          rm -rf *.egg-info

      - name: Build package
        run: python -m build

      - name: Upload package to custom repository
        env:
          TWINE_USERNAME: ${{ secrets.HERA_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.HERA_PASSWORD }}
        run: |
          python -m twine upload --verbose --repository-url https://hera.delmasweb.net dist/*